### ISSUE TITLE
-search-paths getting ignored on windows.

### ISSUE THREAD

**Issue by UnicronNL** [licenseware/ojdm-collector#8]
On https://github.com/licenseware/ojdm-collector/blob/main/ojdmcollector/javafullinfo.go#L12

```javaLibPaths := getJavaSharedLibPaths(nil) // Assuming this function is defined in javasearch.go``` 
It does not pass the searchPaths to this function

changing it to:
```javaLibPaths := getJavaSharedLibPaths(searchPaths) // Assuming this function is defined in javasearch.go```

fixes this issue. but I'm not 100% sure if this fix works in all situations.

**Comment by ciprian-cgr** [comment]
hi @UnicronNL, thanks for raising this! We've created a PR to fix the issue and we will release an updated version shortly. https://github.com/licenseware/ojdm-collector/pull/9
